settings:

  #Русский:
  # Время, которое нужно будет ждать чем повторно др##ить.
  #English:
  # The time it would take to wait than to re-j##k off.

  cooldown: 90

  sounds:
    shoot: "ENTITY_PLAYER_SWIM"
    recharging: "ENTITY_SLIME_JUMP"


messages:
  only-players: "&cТолько для игроков."
  already: "&cВы уже фапаете."
  cooldown: "&cВы устали. Отдохните прежде чем сделать это снова."
  bossbar-title: "Фап-Фап"
  started: "&eВы начали фапать."
  success: "&eВы кончили! Вы управились за %s секунд."
  reload: "&eКонфиг перезагружен."
  disturbed: "&eВас потревожили! Найдите место поукромнее."
  hit-success: "&eОтлично! Прямо в %s."
  were-hit: "&eВ вас попали камшотом!"
  no-perm: "&cНет прав!"

  leaderboard:
    header: "&7Топ &f10 &7по скорости."
    entry: "&e%d. &f%s - &e%s &fсек."
    no-data: "&fНет данных."

  personal-record: "&fЛичный рекорд: &e%s сек."

  pip:
    size:
      smallest: 5
      small: 10
      medium: 17
      big: 22
      biggest: 28

    title:
      fadein: 1
      stay: 100
      fadeout: 10

      smallest: "&c8=D"
      small: "&68==D"
      medium: "&e8===D"
      big: "&a8=====D"
      biggest: "&a8========D"

      subtitle: "&e%d&f см"


